apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: raeburn-brain
spec:
  project: default
  source:
    repoURL: https://example.com/raeburnbrainai.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: raeburn-brain
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
